// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: proto/group/group.proto

package group

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GroupClientClient is the client API for GroupClient service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GroupClientClient interface {
	MessageGroupInfoList(ctx context.Context, in *MessageGroupInfoListRequest, opts ...grpc.CallOption) (*MessageGroupInfoListResponse, error)
}

type groupClientClient struct {
	cc grpc.ClientConnInterface
}

func NewGroupClientClient(cc grpc.ClientConnInterface) GroupClientClient {
	return &groupClientClient{cc}
}

func (c *groupClientClient) MessageGroupInfoList(ctx context.Context, in *MessageGroupInfoListRequest, opts ...grpc.CallOption) (*MessageGroupInfoListResponse, error) {
	out := new(MessageGroupInfoListResponse)
	err := c.cc.Invoke(ctx, "/group.GroupClient/MessageGroupInfoList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GroupClientServer is the server API for GroupClient service.
// All implementations must embed UnimplementedGroupClientServer
// for forward compatibility
type GroupClientServer interface {
	MessageGroupInfoList(context.Context, *MessageGroupInfoListRequest) (*MessageGroupInfoListResponse, error)
	mustEmbedUnimplementedGroupClientServer()
}

// UnimplementedGroupClientServer must be embedded to have forward compatible implementations.
type UnimplementedGroupClientServer struct {
}

func (UnimplementedGroupClientServer) MessageGroupInfoList(context.Context, *MessageGroupInfoListRequest) (*MessageGroupInfoListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MessageGroupInfoList not implemented")
}
func (UnimplementedGroupClientServer) mustEmbedUnimplementedGroupClientServer() {}

// UnsafeGroupClientServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GroupClientServer will
// result in compilation errors.
type UnsafeGroupClientServer interface {
	mustEmbedUnimplementedGroupClientServer()
}

func RegisterGroupClientServer(s grpc.ServiceRegistrar, srv GroupClientServer) {
	s.RegisterService(&GroupClient_ServiceDesc, srv)
}

func _GroupClient_MessageGroupInfoList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageGroupInfoListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupClientServer).MessageGroupInfoList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/group.GroupClient/MessageGroupInfoList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupClientServer).MessageGroupInfoList(ctx, req.(*MessageGroupInfoListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GroupClient_ServiceDesc is the grpc.ServiceDesc for GroupClient service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GroupClient_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "group.GroupClient",
	HandlerType: (*GroupClientServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MessageGroupInfoList",
			Handler:    _GroupClient_MessageGroupInfoList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/group/group.proto",
}
