// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: proto/group/group.proto

package group

import (
	msg "github.com/lifangjunone/proto-example/proto/msg"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取消息页面 群组信息列表
type MessageGroupInfoListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *MessageGroupInfoListRequest) Reset() {
	*x = MessageGroupInfoListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_group_group_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageGroupInfoListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageGroupInfoListRequest) ProtoMessage() {}

func (x *MessageGroupInfoListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_group_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageGroupInfoListRequest.ProtoReflect.Descriptor instead.
func (*MessageGroupInfoListRequest) Descriptor() ([]byte, []int) {
	return file_proto_group_group_proto_rawDescGZIP(), []int{0}
}

func (x *MessageGroupInfoListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type MessageGroupInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId   string       `protobuf:"bytes,1,opt,name=groupId,proto3" json:"groupId,omitempty"`     // 群组id
	AliasName string       `protobuf:"bytes,2,opt,name=aliasName,proto3" json:"aliasName,omitempty"` // 备注
	AvatarUrl string       `protobuf:"bytes,3,opt,name=avatarUrl,proto3" json:"avatarUrl,omitempty"` // 头像
	LastMsg   *msg.ChatMsg `protobuf:"bytes,4,opt,name=lastMsg,proto3" json:"lastMsg,omitempty"`     // 最后一条消息, 注意看这里导入了msg的ChatMsg
}

func (x *MessageGroupInfo) Reset() {
	*x = MessageGroupInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_group_group_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageGroupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageGroupInfo) ProtoMessage() {}

func (x *MessageGroupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_group_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageGroupInfo.ProtoReflect.Descriptor instead.
func (*MessageGroupInfo) Descriptor() ([]byte, []int) {
	return file_proto_group_group_proto_rawDescGZIP(), []int{1}
}

func (x *MessageGroupInfo) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *MessageGroupInfo) GetAliasName() string {
	if x != nil {
		return x.AliasName
	}
	return ""
}

func (x *MessageGroupInfo) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *MessageGroupInfo) GetLastMsg() *msg.ChatMsg {
	if x != nil {
		return x.LastMsg
	}
	return nil
}

type MessageGroupInfoListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*MessageGroupInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *MessageGroupInfoListResponse) Reset() {
	*x = MessageGroupInfoListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_group_group_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageGroupInfoListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageGroupInfoListResponse) ProtoMessage() {}

func (x *MessageGroupInfoListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_group_group_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageGroupInfoListResponse.ProtoReflect.Descriptor instead.
func (*MessageGroupInfoListResponse) Descriptor() ([]byte, []int) {
	return file_proto_group_group_proto_rawDescGZIP(), []int{2}
}

func (x *MessageGroupInfoListResponse) GetList() []*MessageGroupInfo {
	if x != nil {
		return x.List
	}
	return nil
}

var File_proto_group_group_proto protoreflect.FileDescriptor

var file_proto_group_group_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2f, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x1a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x73, 0x67, 0x2f, 0x6d, 0x73, 0x67, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x35, 0x0a, 0x1b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x90, 0x01, 0x0a,
	0x10, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x61,
	0x6c, 0x69, 0x61, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x61, 0x6c, 0x69, 0x61, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x55, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x76,
	0x61, 0x74, 0x61, 0x72, 0x55, 0x72, 0x6c, 0x12, 0x26, 0x0a, 0x07, 0x6c, 0x61, 0x73, 0x74, 0x4d,
	0x73, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x43,
	0x68, 0x61, 0x74, 0x4d, 0x73, 0x67, 0x52, 0x07, 0x6c, 0x61, 0x73, 0x74, 0x4d, 0x73, 0x67, 0x22,
	0x4b, 0x0a, 0x1c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49,
	0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2b, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x32, 0x6e, 0x0a, 0x0b,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x5f, 0x0a, 0x14, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x22, 0x2e, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x33, 0x5a, 0x31,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x69, 0x66, 0x61, 0x6e,
	0x67, 0x6a, 0x75, 0x6e, 0x6f, 0x6e, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x65, 0x78,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_group_group_proto_rawDescOnce sync.Once
	file_proto_group_group_proto_rawDescData = file_proto_group_group_proto_rawDesc
)

func file_proto_group_group_proto_rawDescGZIP() []byte {
	file_proto_group_group_proto_rawDescOnce.Do(func() {
		file_proto_group_group_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_group_group_proto_rawDescData)
	})
	return file_proto_group_group_proto_rawDescData
}

var file_proto_group_group_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_group_group_proto_goTypes = []interface{}{
	(*MessageGroupInfoListRequest)(nil),  // 0: group.MessageGroupInfoListRequest
	(*MessageGroupInfo)(nil),             // 1: group.MessageGroupInfo
	(*MessageGroupInfoListResponse)(nil), // 2: group.MessageGroupInfoListResponse
	(*msg.ChatMsg)(nil),                  // 3: msg.ChatMsg
}
var file_proto_group_group_proto_depIdxs = []int32{
	3, // 0: group.MessageGroupInfo.lastMsg:type_name -> msg.ChatMsg
	1, // 1: group.MessageGroupInfoListResponse.list:type_name -> group.MessageGroupInfo
	0, // 2: group.GroupClient.MessageGroupInfoList:input_type -> group.MessageGroupInfoListRequest
	2, // 3: group.GroupClient.MessageGroupInfoList:output_type -> group.MessageGroupInfoListResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_group_group_proto_init() }
func file_proto_group_group_proto_init() {
	if File_proto_group_group_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_group_group_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageGroupInfoListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_group_group_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageGroupInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_group_group_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageGroupInfoListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_group_group_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_group_group_proto_goTypes,
		DependencyIndexes: file_proto_group_group_proto_depIdxs,
		MessageInfos:      file_proto_group_group_proto_msgTypes,
	}.Build()
	File_proto_group_group_proto = out.File
	file_proto_group_group_proto_rawDesc = nil
	file_proto_group_group_proto_goTypes = nil
	file_proto_group_group_proto_depIdxs = nil
}
